
INSERT INTO recipes (title, servingsize, healthlabels, ingredients, calories, url, image) VALUES
  (
    'Mac and Cheese with Peas',
    4,
    'Low-Fat',
    '3 cups uncooked small macaroni,
        1/2 tablespoon unsalted butter,
        1 small onion, finely chopped,
        2 3/4 cups low-fat (2%) milk,
        2 tablespoons cornstarch,
        1 (10 oz.) box frozen baby peas, thawed,
        1 teaspoon kosher salt,
        2 cups (8 oz.) low-fat cheddar,
        1/4 cup finely grated parmesan,
        Black pepper, to taste',
    2747,
    'http://www.myrecipes.com/recipe/low-fat-mac-cheese-with-peas',
    'https://www.edamam.com/web-img/91d/91d3510ddcfdb567ceb7cbe6dd6e911c.jpg'
  ),
  (
    'Oven Fried Chicken',
    4,
    'Low-Carb',
    '1 whole chicken, 
        cut into 10 pieces, wings reserved for another use,
        1/4 cup low-fat buttermilk,
        1 garlic clove, minced,
        Coarse salt and ground pepper,
        6 slices whole-wheat bread,
        3 tablespoons vegetable oil',
    2871,
    'http://www.marthastewart.com/342382/oven-fried-chicken',
    'https://www.edamam.com/web-img/1a6/1a6c96a2c89440fbe504b64b1fdef03c.jpg'
  ),
  (
    'Vegetarian Lasagna',
    6,
    'Vegetarian',
    '1 lb no-boil lasagna noodles,
        5 cups (usually 1 1/2 jars) of tomato sauce (i like whole foods 365 brand, no added sugars or preservatives),
        1 15-oz package of extra firm tofu,
        1 cup ricotta cheese,
        2 cups shredded mozzarella cheese,
        3/4 cups shredded parmesan cheese,
        1 15-oz can jarred roasted peppers (or roast 2 red peppers yourself),
        1/2 tsp smoked paprika,
        1/8 tsp nutmeg,
        Salt and pepper to taste',
    4216,
    'http://www.thekitchn.com/recipe-to-feed-157866',
    'https://www.edamam.com/web-img/4a6/4a6c509c9a5b4420103d889eef592606.jpg'
  ),
  (
    'Vegetarian Reuben',
    2,
    'Vegetarian',
    '4 slices rye or pumpernickel bread,
        4 slices swiss cheese (lacey, baby, or regular),
        10 to 15 button mushrooms (cleaned and sliced),
        1/4 head red cabbage (sliced),
        2 cloves garlic (minced),
        3 tablespoons mayonnaise,
        2 tablespoons dijon mustard,
        2 tablespoons dill pickle relish,
        2 tablespoons prepared horseradish,
        1/4 cup apple cider vinegar,
        Sea salt and freshly ground black pepper,
        Unsalted butter,
        Olive oil',
    1367,
    'https://food52.com/recipes/11477-vegetarian-reuben',
    'https://www.edamam.com/web-img/b1f/b1f04b25bb47ad8eae387b747bb4ec24.JPG'
  ),
  (
    'Nachos with Avocado',
    4,
    'Vegetarian',
    '1 bag corn tortilla chips,
        1½ cups go veggie! vegan mexican cheese shreds,
        1 cup fresh salsa,
        ½ cup packed baby spinach,
        1 extra ripe avocado, peeled, pitted and mashed,
        ½ tsp. sea salt,
        ½ tsp. freshly ground pepper,
        ½ tsp. crushed red pepper flakes,
        1 tbsp. sesame seeds,
        ½ cup finely chopped cilantro, for topping',
    2813,
    'http://honestcooking.com/dairy-free-vegan-nachos-recipe/',
    'https://www.edamam.com/web-img/ed3/ed32750be9cc9b518e464a812c533f59.jpg'
  ),
  (
    'Easy Pan Pizza',
    4,
    'Vegan',
    '1 recipe square pan pizza dough recipe,
        1/4 cup extra-virgin olive oil,
        2 large onions, finely sliced (about 3 cups),
        Kosher salt and freshly ground black pepper,
        2 cups panko-style vegan breadcrumbs,
        1 (28-ounce can) whole peeled tomatoes, preferably san marzano, drained,
        1 cup oil-packed sun dried tomatoes, drained, roughly chopped,
        3/4 cup pitted olives, roughly chopped,
        1 handful roughly torn basil leaves',
    2559,
    'http://www.seriouseats.com/recipes/2013/02/easy-party-pan-pizza-sun-dried-tomatoes-olives-caramelized-onions-sfinzione-sicilian-recipe.html',
    'https://www.edamam.com/web-img/517/51759dfef0616301acedae55983a2be7.jpg'
  ),
  (
    'Vegan Corn Tamales',
    3,
    'Low-Fat',
    '2 x ears of fresh corn ,save the husks,
        2 cup water,
        1 tsp salt,
        2 tsp olive oil,
        2 cup masa harina,
        1 can black beans,
        1 can pinto beans,
        1 small onion diced,
        2 x garlic clove, minced,
        1 x tomato, diced,
        1 tsp cumin,
        1 tsp chili powder,
        2 x kernels from corn,
        Handful cilantro. chopped,
        1 x serrano chili, minced',
    1924,
    'http://www.thekitchn.com/how-to-make-vegan-corn-tamales-85314',
    'https://www.edamam.com/web-img/49f/49fa65a8ca1da424b4dd581bcf0d3f45.jpg'
  ),
  (
    'Low Carb Burgers',
    4,
    'Low-Carb',
    '2 lbs ground chuck,
        1 tsp kosher salt,
        1/2 tsp black pepper,
        5 dashes worcestershire sauce,
        2 tbsps butter,
        1/4 cup mayonnaise,
        1 tbsp dijon mustard,
        2 dashes worcestershire sauce,
        2 whole avocados, sliced,
        1 whole tomatoes, sliced,
        1/4 whole thinly sliced red onion,
        1 head iceberg, green leaf, or butter lettuce,
        Optional toppings: chopped pickles, feta cheese, cilantro, pico de gallo',
    2494,
    'http://thepioneerwoman.com/cooking/low-carb-burgers/',
    'https://www.edamam.com/web-img/48d/48d739e78eec26745dd2e4b5420c99f7.jpg'
  ),
  (
    'Salade Nicoise',
    4,
    'High-Protein',
    '4 cups high protein flour,
        3 teaspoons sea salt,
        1 teaspoon instant yeast,
        28 ounces can whole pealed tomatoes,
        1 clove garlic,
        1/4 cup extra virgin olive oil',
    2457,
    'https://food52.com/recipes/15117-home-made-pizza-that-s-crispy-on-the-bottom-chewy-in-the-middle',
    'https://www.edamam.com/web-img/831/831bc818954855f880593bffa3b8053e.JPG'
  ),
   (
    'Gluten-Free Croque-Monsieur',
    4,
    'Gluten-Free',
    '8 slices gluten-free white sandwich bread, homemade or store-bought,
        2 tablespoons unsalted butter,
        3 tablespoons sweet rice flour,
        2 1/2 cups whole or 2% milk, warmed,
        1/4 teaspoon salt,
        1/2 teaspoon freshly ground black pepper,
        8 ounces gruyère cheese, grated (about 2 cups),
        1/4 cup freshly grated parmesan cheese,
        Dijon mustard,
        1/2 pound thinly sliced ham',
    2613,
    'http://www.seriouseats.com/recipes/2012/01/gluten-free-croque-monsieur-recipe.html',
    'https://www.edamam.com/web-img/53e/53e09351b216cad48fc5afd9fd58d175.jpg'
  ),
    (
    'Gluten-Free Apple and Almond Cake',
    6,
    'Gluten-Free',
    '3 sharp eating apples, peeled, cored and chopped,
        1 lemon, juice only,
        300g/10½g golden caster sugar,
        8 free-range eggs,
        325g/11½oz ground almonds,
        ½ tsp almond essence,
        50g/2oz flaked almonds,
        Icing sugar, for sprinkling',
    4202,
    'http://www.bbc.co.uk/food/recipes/gluten-free_apple_and_22345',
    'https://www.edamam.com/web-img/c38/c38cf225fb62a6ca2f36e9ba28db1b86.jpg'
  ),
  (
    'Gluten-Free Lemon and Almond Cake',
    6,
    'Gluten-Free',
    '4 eggs,
        2/3 cups caster sugar,
        125g extra soft butter, or dairy-free margarine,
        2 3/4 cups (300g) ground almonds,
        1/3 cup (50g) brown rice flour,
        1 teaspoon baking powder,
        The zest of 1 lemon,
        4 stalks of rhubarb (approx 150g),
        2 teaspoons caster sugar, extra,
        Powdered sugar for dusting',
    3698,
    'https://food52.com/recipes/12553-gluten-free-rhubarb-lemon-and-almond-cake',
    'https://www.edamam.com/web-img/574/574cd5f04053643d98d05f792894e38c.jpg'
  );